spring:
  application:
    name: gateway
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.10:8848
    sentinel:
      transport:
        dashboard: 192.168.1.10:8085
        port: 8085
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        # 采用自定义路由 ID（有固定用法，不同的 id 有不同的功能，详见：https://cloud.spring.io/spring-cloud-gateway/2.0.x/single/spring-cloud-gateway.html#gateway-route-filters）
        - id: service
          # 采用 LoadBalanceClient 方式请求，以 lb:// 开头，后面的是注册在 nacos 上的服务名
          uri: lb://service
          # Predicate 翻译过来是“谓词”的意思，必须，主要作用是匹配用户的请求，有很多种用法
          predicates:
            # 路径匹配，以api开头，直接配置是不生效的，看filters
            - Path=/api/user/**
          filters:
            # 前缀过滤，默认配置下，我们的请求路径是 http://localhost:8888/service/** 这时会路由到指定的服务
            # 此处配置去掉 1 个路径前缀，再配置上面的 Path=/api/**，就能按照 http://localhost:8888/api/** 的方式访问了
            - StripPrefix=1

server:
  port: 8888

logging:
  level:
    org.springframework.cloud.gateway: debug