spring:
  application:
    name: demo
  datasource:
    url: jdbc:mysql://192.168.1.100:13306/mall?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

server:
  port: 8080

